### ISSUE TITLE
Doggerina

### ISSUE THREAD

**Issue by byronmejia** [byronmejia/memes#1]
This issue is for storing memes that follow the doggerina template only.

**Comment by byronmejia** [comment]
```yaml
title: Shooberina
tags:
- cute
- dog
```
![image](https://user-images.githubusercontent.com/11262664/27024270-3baef1fc-4f99-11e7-9cea-2d0ddbf78404.png)

**Comment by byronmejia** [comment]
```yaml
title: pugerina
tags:
- pug
- cute
- heck my life
```

![image](https://user-images.githubusercontent.com/11262664/27024327-80349cdc-4f99-11e7-9ebf-198758da69d2.png)

**Comment by byronmejia** [comment]
```yaml
tags:
- shoob
- heck
```

![image](https://user-images.githubusercontent.com/11262664/27024477-0ceb09c2-4f9a-11e7-8293-487c712843d7.png)

**Comment by byronmejia** [comment]
```yaml
title: doggerina
tags:
- heck
- your
-lyf
```

![image](https://user-images.githubusercontent.com/11262664/27024519-36ac2f34-4f9a-11e7-8492-89d1050be9a7.png)
